### ISSUE TITLE
just wanna say thanks and then some...

### ISSUE THREAD

**Issue by braveheartleo** [gwlim/mips24k-barrier-breaker-patch#2]
Hi gwlim,

I want to thank you for compiling these patches and making them available. I have been successfully using some patches I have cherry picked with my custom Barrier Breaker compile of the MIPS24Kec ramips.rt305x-based Asus RT-N13U ver.B1 router, carefully modifying relevant sections in the patches, like the use of `mips24kec` instead of `mips24kc`.

Here are the patches I'm currently using:
> 00-disable-mips16-by-default.patch
> 01-add-24kec-cpu-optimization-default-package.patch
024-ltq-optimization.patch
026-kernel-mtune-24kec.patch
032-kernel-config.patch
033-config-3.10-generic.patch
034-toolchain-config.patch
037-fix-l7-filter.patch
039-disable-tls-util-linux.patch
03-wireless-tweak-unlock.patch
044-patch-uclibc-mips32r2.patch
045-patch-uclibc-nodebug-thread.patch
04-disable-wireless-debug.patch
050-update-gcc-4.8.4-linaro.patch
051-binutil-linaro-update.patch
052-set-linaro-binutil-default.patch
055-no-hz-idle.patch
060-add-fix-mips-noexecstack.patch
060-remove-arch-kernel-debug.patch
061-gcc-toolchain.patch
065-refresh-decompress-kernel-patch.patch
06-remove-qos-ipv4-only-filter.patch
070-kernel-version.patch
099-hostapd-use-fast-math.patch
102-update-lzo.patch
103-enable-openssl-thread.patch
204-backport-add-netfilter-routing-cache.patch
910-remove-linux-gcc-sortname.patch
912-use-optimized-uclibc-strstr.patch
955-add-dd-wrt-openssl-mips32r2-asm.patch

One note however is that the patchfile `target/linux/ramips/patches-3.10/0203-MIPS-Fix-accessing-to-per-cpu-data-when-flushing-the.patch` is no longer needed as the changes in this patch have been integrated in later kernel 3.10 point releases. One must remove the said file or the kernel compile section will fail.

No other issues apart from that, but if I do encounter some I will be sure to report.

There is a new kernel release, 3.10.65 and I have successfully rebuilt and ran my custom firmware with this kernel.

Thanks again,
ianp

**Comment by gwlim** [comment]
No problem, anyway you can take the whole patch batch because if the target is different the addition patch code is ignored.
