### ISSUE TITLE
openssl 1.0.2 doesn't compile in BB, complains about missing zlib.h

### ISSUE THREAD

**Issue by braveheartleo** [gwlim/mips24k-barrier-breaker-patch#3]
You can view the relevant error message, preserving the indentations, on pastebin. This is encountered using a `target/linux/ramips/rt305x` profile.

http://pastebin.com/8QC38vr3

**Comment by gwlim** [comment]
FIrst try make dirclean && make defconfig && make V=s
If it still errors can you try deleting the whole folder and start over?
Sometime the configuration got corrupted and my patcher is meant for ease of starting over.

**Comment by gwlim** [comment]
Tips:
Keep all your downloaded sources in 1 directory and symlink to the buildroot when you rebuild this will save your download time and make recompiling lightning fast

**Comment by braveheartleo** [comment]
It appears that my BB buildroot got dirty, and I had to restart again from scratch. openssl 1.0.2 compiles successfully now.
