### ISSUE TITLE
037-fix-L7-filter.patch patch is not compatible with 3.18 kernel

### ISSUE THREAD

**Issue by qiuzi** [gwlim/mips24k-barrier-breaker-patch#4]
Into several tests use L7 3.18 kernel patches can cause kernel error
Error reporting:
  131.470000] Kernel bug detected[#1]:
[  131.470000] CPU: 0 PID: 3 Comm: ksoftirqd/0 Not tainted 3.18.9 #1
[  131.470000] task: 838289b0 ti: 8383c000 task.ti: 8383c000
[  131.470000] $ 0   : 00000000 00000000 81059580 00000001
[  131.470000] $ 4   : 00000000 00000100 829d9800 0000001d
[  131.470000] $ 8   : 0020001e 8280b380 00000020 0020001e
[  131.470000] $12   : 7f9edb90 00822570 0082312c 77b6d068
[  131.470000] $16   : 8318d824 8004b100 0000000a 0000000a
[  131.470000] $20   : 00000100 80340000 8034ac04 00000009
[  131.470000] $24   : 77aed3a0 800ae810                  
[  131.470000] $28   : 8383c000 8383de18 00000024 8004b0f0
[  131.470000] Hi    : 00000001
[  131.470000] Lo    : 00000001
[  131.470000] epc   : 80148474 kfree+0x64/0x11c
[  131.470000]     Not tainted
[  131.470000] ra    : 8004b0f0 __rcu_process_callbacks+0x9c/0xd8
[  131.470000] Status: 1100e403 KERNEL EXL IE 
[  131.470000] Cause : 10800034
[  131.470000] PrId  : 0001964c (MIPS 24KEc)
[  131.470000] Modules linked in: ifb rt2800soc rt2800mmio rt2800lib pppoe ppp_async iptable_nat rt2x00soc rt2x00mmio rt2x00lib pptp pppox ppp_mppe ppp_generic nf_nat_ipv4 nf_conntrack_ipv4 mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_layer7 xt_id xt_hl xt_helper xt_geoip xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY ts_kmp ts_fsm ts_bm slhc nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat_irc nf_nat_ftp nf_nat nf_log_ipv4 nf_log_common nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack_irc nf_conntrack_ftp macvlan iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables crc_itu_t crc_ccitt compat act_connmark nf_conntrack act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_hfsc sch_ingress ledtrig_usbdev xt_set x_tables ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip_gre gre ip_tunnel nls_utf8 eeprom_93cx6 sha1_generic ecb arc4 crypto_blkcipher usb_storage leds_gpio xhci_plat_hcd xhci_hcd dwc2_platform dwc2 sd_mod scsi_mod gpio_button_hotplug ext4 crc16 jbd2 mbcache usbcore nls_base usb_common crypto_hash [last unloaded: ifb]
[  131.470000] Process ksoftirqd/0 (pid: 3, threadinfo=8383c000, task=838289b0, tls=00000000)
[  131.470000] Stack : 801f06d4 802e0000 802d9170 802de794 00000010 00000200 8034ac28 801bc02c
          838289e0 802d9170 802e0000 8214b578 802d9170 800343a8 838289b0 800ae7bc
          10804000 838289b0 838289b0 802ee344 04208040 ffffbe2c 83819d00 802ee344
          00000001 00000002 801f06d4 802e0000 802d9170 802de794 00000000 801cb3c0
          801f06d4 802e0000 802d9170 802de794 00000000 801f0808 83819d80 83819d00
          ...
[  131.470000] Call Trace:
[  131.470000] [<80148474>] kfree+0x64/0x11c
[  131.470000] [<8004b0f0>] __rcu_process_callbacks+0x9c/0xd8
[  131.470000] [<801bc02c>] rcu_process_callbacks+0x14/0x28
[  131.470000] [<800343a8>] __do_softirq+0xf8/0x230
[  131.470000] [<801cb3c0>] run_ksoftirqd+0x28/0x50
[  131.470000] [<801f0808>] smpboot_thread_fn+0x134/0x164
[  131.470000] [<8014ceac>] kthread+0xd8/0xe4
[  131.470000] [<80004478>] ret_from_kernel_thread+0x14/0x1c
[  131.470000] 
[  131.470000] 
Code: 8c430000  3063c000  2c630001 <00030336> 8c450000  7ca50380  10a00002  00000000  8c450038 
[  132.110000] ---[ end trace 82e2456d86de7db2 ]---
[  132.120000] Kernel panic - not syncing: Fatal exception in interrupt
[  132.120000] Rebooting in 3 seconds..

[  124.960000] Kernel bug detected[#1]:
[  124.960000] CPU: 0 PID: 0 Comm: swapper Not tainted 3.18.9 #1
[  124.960000] task: 802dfb30 ti: 802d4000 task.ti: 802d4000
[  124.960000] $ 0   : 00000000 00000000 81045b20 00000001
[  124.960000] $ 4   : 00000000 00000044 82006000 8202d3f8
[  124.960000] $ 8   : 9c2ca07d 8202d1d0 00000011 0011000e
[  124.960000] $12   : 0000001d 00000003 00000000 00000003
[  124.960000] $16   : 8202d3a0 000001bf 8202d3a0 802de900
[  124.960000] $20   : 00000000 000002c0 802de900 8202d3e0
[  124.960000] $24   : 00000000 80242324                  
[  124.960000] $28   : 802d4000 802d5cc0 8202d3b0 831606d0
[  124.960000] Hi    : 000002c0
[  124.960000] Lo    : 9b04c400
[  124.960000] epc   : 80148474 kfree+0x64/0x11c
[  124.960000]     Not tainted
[  124.960000] ra    : 831606d0 nf_conntrack_find_get+0x8c/0xc8 [nf_conntrack]
[  124.960000] Status: 1100e403 KERNEL EXL IE 
[  124.960000] Cause : 10800034
[  124.960000] PrId  : 0001964c (MIPS 24KEc)
[  124.960000] Modules linked in: ifb rt2800soc rt2800mmio rt2800lib pppoe ppp_async iptable_nat rt2x00soc rt2x00mmio rt2x00lib pptp pppox ppp_mppe ppp_generic nf_nat_ipv4 nf_conntrack_ipv4 mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_layer7 xt_id xt_hl xt_helper xt_geoip xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY ts_kmp ts_fsm ts_bm slhc nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat_irc nf_nat_ftp nf_nat nf_log_ipv4 nf_log_common nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack_irc nf_conntrack_ftp macvlan iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables crc_itu_t crc_ccitt compat act_connmark nf_conntrack act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_hfsc sch_ingress ledtrig_usbdev xt_set x_tables ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip_gre gre ip_tunnel nls_utf8 eeprom_93cx6 sha1_generic ecb arc4 crypto_blkcipher usb_storage leds_gpio xhci_plat_hcd xhci_hcd dwc2_platform dwc2 sd_mod scsi_mod gpio_button_hotplug ext4 crc16 jbd2 mbcache usbcore nls_base usb_common crypto_hash [last unloaded: ifb]
[  124.960000] Process swapper (pid: 0, threadinfo=802d4000, task=802dfb30, tls=00000000)
[  124.960000] Stack : 8202d2b8 00000192 8202d2b8 802de900 8202d3a0 831607cc 1832598b 802d9690
          0000001d 80224f78 000001bf 80179334 83fdc000 802e0000 00000000 000001bf
          000001bf 831613dc 0000000c 00000002 00000000 00000000 00000100 802e0000
          83161410 80342d78 00200200 000000a0 8034ac04 00000001 00000004 8008e7a4
          83fdc000 802e1e54 802e0000 00000000 00000007 00000001 80342560 802e0000
          ...
[  124.960000] Call Trace:
[  124.960000] [<80148474>] kfree+0x64/0x11c
[  124.960000] [<831606d0>] nf_conntrack_find_get+0x8c/0xc8 [nf_conntrack]
[  124.960000] 
[  124.960000] 
Code: 8c430000  3063c000  2c630001 <00030336> 8c450000  7ca50380  10a00002  00000000  8c450038 
[  125.540000] ---[ end trace d0bbe38d5d6d3a7f ]---
[  125.550000] Kernel panic - not syncing: Fatal exception in interrupt
[  125.550000] Rebooting in 3 seconds.

[  166.880000] Kernel bug detected[#2]:
[  166.880000] CPU: 0 PID: 0 Comm: swapper Tainted: G      D W      3.18.9 #1
[  166.880000] task: 802dfb30 ti: 802d4000 task.ti: 802d4000
[  166.880000] $ 0   : 00000000 00000000 00000001 00000014
[  166.880000] $ 4   : 80342618 8281b108 ffffcc00 00000001
[  166.880000] $ 8   : 007dffef f5613b63 00989680 00000000
[  166.880000] $12   : 00000026 00000004 00000000 00000004
[  166.880000] $16   : 802d5d48 00380000 0000000c 80342560
[  166.880000] $20   : fffffffc 00000000 8034ac04 00000001
[  166.880000] $24   : 00000000 80242324                  
[  166.880000] $28   : 802d4000 802d5d38 00000004 801cbaa4
[  166.880000] Hi    : 00000001
[  166.880000] Lo    : 00000001
[  166.880000] epc   : 8008fd44 cascade+0x74/0xac
[  166.880000]     Tainted: G      D W     
[  166.880000] ra    : 801cbaa4 run_timer_softirq+0xe8/0x1f8
[  166.880000] Status: 1100e402 KERNEL EXL 
[  166.880000] Cause : 10800034
[  166.880000] PrId  : 0001964c (MIPS 24KEc)
[  166.880000] Modules linked in: ifb rt2800soc rt2800mmio rt2800lib pppoe ppp_async iptable_nat rt2x00soc rt2x00mmio rt2x00lib pptp pppox ppp_mppe ppp_generic nf_nat_ipv4 nf_conntrack_ipv4 mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_layer7 xt_id xt_hl xt_helper xt_geoip xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY ts_kmp ts_fsm ts_bm slhc nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat_irc nf_nat_ftp nf_nat nf_log_ipv4 nf_log_common nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack_irc nf_conntrack_ftp macvlan iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables crc_itu_t crc_ccitt compat act_connmark nf_conntrack act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_hfsc sch_ingress ledtrig_usbdev xt_set x_tables ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip_gre gre ip_tunnel nls_utf8 eeprom_93cx6 sha1_generic ecb arc4 crypto_blkcipher usb_storage leds_gpio xhci_plat_hcd xhci_hcd dwc2_platform dwc2 sd_mod scsi_mod gpio_button_hotplug ext4 crc16 jbd2 mbcache usbcore nls_base usb_common crypto_hash [last unloaded: ifb]
[  166.880000] Process swapper (pid: 0, threadinfo=802d4000, task=802dfb30, tls=00000000)
[  166.880000] Stack : 00000000 00000000 83fdc000 802e1e54 82bfc158 838e3b0c 80342560 802e0000
          802d5d78 80342d78 00200200 801cbaa4 8029e8e0 80108e08 ffffcc01 802d8d50
          00000008 8034ac10 0000000a 00000002 8034ac08 0000000a 00000002 00000100
          80340000 800343a8 83fdc000 00000000 83fdc000 80109a2c 00000000 00000000
          00200000 ffffcc01 00000000 00000001 8029e2c8 00000001 83fdc000 00000000
          ...
[  166.880000] Call Trace:
[  166.880000] [<8008fd44>] cascade+0x74/0xac
[  166.880000] [<801cbaa4>] run_timer_softirq+0xe8/0x1f8
[  166.880000] [<800343a8>] __do_softirq+0xf8/0x230
[  166.880000] [<8012f570>] irq_exit+0x54/0x70
[  166.880000] [<80004430>] ret_from_irq+0x0/0x4
[  166.880000] [<80004680>] __r4k_wait+0x20/0x40
[  166.880000] [<800a4b00>] cpu_startup_entry+0xf0/0x13c
[  166.880000] [<802f1b5c>] start_kernel+0x42c/0x444
[  166.880000] 
[  166.880000] 
Code: 00541024  02621026  0002102b <00020336> 0c00ef67  02602021  02202821  08023f4b  8e310000 
[  167.510000] ---[ end trace c81e44a8aa3e44e5 ]---
[  167.530000] Kernel panic - not syncing: Fatal exception in interrupt
[  167.530000] Rebooting in 3 seconds..

**Comment by gwlim** [comment]
Will work on it when Chaos Calmer is released

**Comment by qiuzi** [comment]
OpenWrt has removed L7 support

2015-05-04 20:15 GMT+08:00 gwlim <notifications@github.com>:

**Comment by gwlim** [comment]
As long as the commit history is there it is possible to add a patch to add it back

**Comment by qiuzi** [comment]
Problem is that kernel 3.18 L7 incompatible system using

2015-05-04 21:33 GMT+08:00 gwlim <notifications@github.com>:

**Comment by gwlim** [comment]
Hi please take a look at 
https://github.com/gwlim/mips24k-chaos-calmer-patch
Added back L7 Protocol which upstream removed and refresh with Chaos Calmer Kernel 3.18
Tested WORKING with bittorrent
```
Sat May 23 09:53:00 2015 kern.warn kernel: [  215.396000] P2PBLOCK-seen-bit:IN=eth0.2 OUT=br-lan MAC=XX:00:00:60 SRC=X.X.X.X DST=192.168.1.133 LEN=96 TOS=0x00 PREC=0x00 TTL=111 ID=31249 PROTO=UDP SPT=23643 DPT=51413 LEN=76 MARK=0xff00 
Sat May 23 09:53:01 2015 kern.warn kernel: [  216.272000] P2PBLOCK-seen-bit:IN=eth0.2 OUT=br-lan MAC=XX:00:00:83 SRC=X.X.X.X DST=192.168.1.133 LEN=131 TOS=0x00 PREC=0x00 TTL=111 ID=28872 PROTO=UDP SPT=41548 DPT=51413 LEN=111 MARK=0xff00 
Sat May 23 09:53:08 2015 kern.warn kernel: [  223.668000] P2PBLOCK-seen-bit:IN=eth0.2 OUT=br-lan MAC=XX:00:00:83 SRC=X.X.X.X DST=192.168.1.133 LEN=131 TOS=0x00 PREC=0x00 TTL=108 ID=24962 PROTO=UDP SPT=40290 DPT=51413 LEN=111 MARK=0xff00 
Sat May 23 09:53:08 2015 kern.warn kernel: [  223.692000] P2PBLOCK-DROP:IN=eth0.2 OUT=br-lan MAC=XX:00:00:83 SRC=X.X.X.X DST=192.168.1.133 LEN=131 TOS=0x00 PREC=0x00 TTL=108 ID=24962 PROTO=UDP SPT=40290 DPT=51413 LEN=111 MARK=0xff00 
Sat May 23 09:53:08 2015 kern.warn kernel: [  223.692000] P2PBLOCK-DROP:IN=eth0.2 OUT=br-lan MAC=XX:00:00:30 SRC=X.X.X.X DST=192.168.1.133 LEN=48 TOS=0x00 PREC=0x00 TTL=108 ID=24964 PROTO=UDP SPT=40290 DPT=51413 LEN=28 MARK=0xff00 
Sat May 23 09:53:08 2015 kern.warn kernel: [  223.692000] P2PBLOCK-DROP:IN=eth0.2 OUT=br-lan MAC=XX:00:00:30 SRC=X.X.X.X DST=192.168.1.133 LEN=48 TOS=0x00 PREC=0x00 TTL=109 ID=11864 PROTO=UDP SPT=24064 DPT=51413 LEN=28 MARK=0xff00 
Sat May 23 09:53:08 2015 kern.warn kernel: [  223.692000] P2PBLOCK-DROP:IN=eth0.2 OUT=br-lan MAC=XX:00:01:78 SRC=X.X.X.X DST=192.168.1.133 LEN=376 TOS=0x00 PREC=0x00 TTL=109 ID=11868 PROTO=UDP SPT=24064 DPT=51413 LEN=356 MARK=0xff00 
Sat May 23 09:53:08 2015 kern.warn kernel: [  223.832000] P2PBLOCK-DROP:IN=eth0.2 OUT=br-lan MAC=XX:00:00:30 SRC=X.X.X.X DST=192.168.1.133 LEN=48 TOS=0x00 PREC=0x00 TTL=107 ID=32718 PROTO=UDP SPT=6881 DPT=51413 LEN=28 MARK=0xff00 
Sat May 23 09:53:15 2015 kern.warn kernel: [  230.564000] P2PBLOCK-seen-bit:IN=eth0.2 OUT=br-lan MAC=XX:00:02:d3 SRC=X.X.X.X DST=192.168.1.133 LEN=723 TOS=0x00 PREC=0x00 TTL=46 ID=43479 DF PROTO=UDP SPT=51413 DPT=51413 LEN=703 MARK=0xff00 
Sat May 23 09:53:15 2015 kern.warn kernel: [  230.584000] P2PBLOCK-seen-bit:IN=eth0.2 OUT=br-lan MAC=XX:00:01:b3 SRC=X.X.X.X DST=192.168.1.133 LEN=435 TOS=0x00 PREC=0x00 TTL=46 ID=29493 PROTO=UDP SPT=61137 DPT=51413 LEN=415 MARK=0xff00 
```

**Comment by qiuzi** [comment]
070-kernel-version.patch and 037-fix-L7-filter.patch patch on it?

**Comment by gwlim** [comment]
Yes and check çc_openwrt.sh to restore the missing *.pat files

**Comment by gwlim** [comment]
010-add-back-l7filter.

**Comment by qiuzi** [comment]
Layer7 cause kernel error, cannot normally use

**Comment by gwlim** [comment]
I already tested it, with p2pblock, works use chao calmer not barrier breaker.

**Comment by qiuzi** [comment]
R45715 source code

I just add 070 037 patch, other patches are not also need to be added?
Only need Layer7 module what patch?

**Comment by gwlim** [comment]
010-add-back-l7.patch
037-fix-l7-filter.patch

**Comment by qiuzi** [comment]
These two patches not working, affecting a kernel panic

**Comment by gwlim** [comment]
I am not getting any kernel panic, not sure what you did.

**Comment by qiuzi** [comment]
Have anything to do with the 033-config-3.10-generic.patch?

**Comment by gwlim** [comment]
Why don't you use my branch to built it yourself to find out.
